// Copyright © 2025 Ping Identity Corporation

// Code generated by ping-terraform-plugin-framework-generator

package keypairsoauthopenidconnect_test

import (
	"fmt"
	"testing"

	"github.com/hashicorp/terraform-plugin-framework/providerserver"
	"github.com/hashicorp/terraform-plugin-go/tfprotov6"
	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/pingidentity/terraform-provider-pingfederate/internal/acctest"
	"github.com/pingidentity/terraform-provider-pingfederate/internal/provider"
	"github.com/pingidentity/terraform-provider-pingfederate/internal/version"
)

func TestAccKeypairsOauthOpenidConnect_MinimalMaximal(t *testing.T) {
	resource.Test(t, resource.TestCase{
		PreCheck: func() { acctest.ConfigurationPreCheck(t) },
		ProtoV6ProviderFactories: map[string]func() (tfprotov6.ProviderServer, error){
			"pingfederate": providerserver.NewProtocol6WithError(provider.NewTestProvider()),
		},
		Steps: []resource.TestStep{
			{
				// Create the resource with a minimal model
				Config: keypairsOauthOpenidConnect_MinimalHCL(),
				Check:  keypairsOauthOpenidConnect_CheckComputedValuesMinimal(),
			},
			{
				// Update to a complete model
				Config: keypairsOauthOpenidConnect_CompleteHCL(),
				Check:  keypairsOauthOpenidConnect_CheckComputedValuesComplete(),
			},
			{
				// Test importing the resource
				Config:                               keypairsOauthOpenidConnect_CompleteHCL(),
				ResourceName:                         "pingfederate_keypairs_oauth_openid_connect.example",
				ImportStateVerifyIdentifierAttribute: "static_jwks_enabled",
				ImportState:                          true,
				ImportStateVerify:                    true,
			},
			{
				// Back to minimal model
				Config: keypairsOauthOpenidConnect_MinimalHCL(),
				Check:  keypairsOauthOpenidConnect_CheckComputedValuesMinimal(),
			},
		},
	})
}

func keypairsOauthOpenidConnect_VersionRestrictedHCL() string {
	var versionedHcl string
	if acctest.VersionAtLeast(version.PingFederate1201) {
		versionedHcl += `
  p256_active_key_id = "ec256active"
  p256_decryption_active_key_id = "ec256decryptactive"
  p256_decryption_previous_key_id = "ec256decryptprevious"
  p256_previous_key_id = "ec256previous"
  p384_active_key_id = "ec384active"
  p384_decryption_active_key_id = "ec384decryptactive"
  p384_decryption_previous_key_id = "ec384decryptprevious"
  p384_previous_key_id = "ec384previous"
  p521_active_key_id = "ec521active"
  p521_decryption_active_key_id = "ec521decryptactive"
  p521_decryption_previous_key_id = "ec521decryptprevious"
  p521_previous_key_id = "ec521previous"
  rsa_active_key_id = "rsaactive"
  rsa_decryption_active_key_id = "rsadecryptactive"
  rsa_decryption_previous_key_id = "rsadecryptprevious"
  rsa_previous_key_id = "rsaprevious"
  rsa_algorithm_active_key_ids = [
    {
      key_id       = "rsalistactive"
      rsa_alg_type = "RS256"
    }
  ]
  rsa_algorithm_previous_key_ids = [
    {
      key_id       = "rsalistpreviousone"
      rsa_alg_type = "RS384"
    },
    {
      key_id       = "rsalistprevioustwo"
      rsa_alg_type = "RS512"
    }
  ]
`
	}
	if acctest.VersionAtLeast(version.PingFederate1230) {
		versionedHcl += `
  dynamic_key_certificate_information = {
    city              = "Austin"
    country           = "US"
    organization      = "Example Organization"
    organization_unit = "Example Organizational Unit"
    state             = "TX"
  }
  publish_dynamic_key_x5cs = true
`
	}
	return versionedHcl
}

// Minimal HCL with only required values set
func keypairsOauthOpenidConnect_MinimalHCL() string {
	return fmt.Sprintf(`
resource "pingfederate_keypairs_oauth_openid_connect" "example" {
  static_jwks_enabled = false
}
`)
}

// Maximal HCL with all values set where possible
func keypairsOauthOpenidConnect_CompleteHCL() string {
	return fmt.Sprintf(`
resource "pingfederate_keypairs_oauth_openid_connect" "example" {
  p256_active_cert_ref = {
    id = "ec256active"
  }
  p256_decryption_active_cert_ref = {
    id = "ec256active"
  }
  p256_decryption_previous_cert_ref = {
    id = "ec256previous"
  }
  p256_decryption_publish_x5c_parameter = true
  p256_previous_cert_ref = {
    id = "ec256previous"
  }
  p384_active_cert_ref = {
    id = "ec384active"
  }
  p384_decryption_active_cert_ref = {
    id = "ec384active"
  }
  p384_decryption_previous_cert_ref = {
    id = "ec384previous"
  }
  p384_decryption_publish_x5c_parameter = true
  p384_previous_cert_ref = {
    id = "ec384previous"
  }
  p521_active_cert_ref = {
    id = "ec521active"
  }
  p521_decryption_active_cert_ref = {
    id = "ec521active"
  }
  p521_decryption_previous_cert_ref = {
    id = "ec521previous"
  }
  p521_previous_cert_ref = {
    id = "ec521previous"
  }
  p521_publish_x5c_parameter = true
  rsa_active_cert_ref = {
    id = "419x9yg43rlawqwq9v6az997k"
  }
  rsa_decryption_active_cert_ref = {
    id = "419x9yg43rlawqwq9v6az997k"
  }
  rsa_decryption_previous_cert_ref = {
    id = "rsaprevious"
  }
  rsa_previous_cert_ref = {
    id = "rsaprevious"
  }
  rsa_publish_x5c_parameter = true
  static_jwks_enabled       = true
  %s
}
`, keypairsOauthOpenidConnect_VersionRestrictedHCL())
}

// Validate any computed values when applying minimal HCL
func keypairsOauthOpenidConnect_CheckComputedValuesMinimal() resource.TestCheckFunc {
	var versionedChecks []resource.TestCheckFunc
	if acctest.VersionAtLeast(version.PingFederate1201) {
		versionedChecks = append(versionedChecks,
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_active_key_ids.#", "0"),
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_previous_key_ids.#", "0"),
		)
	} else {
		versionedChecks = append(versionedChecks,
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_active_key_ids"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_previous_key_ids"),
		)
	}
	if acctest.VersionAtLeast(version.PingFederate1230) {
		versionedChecks = append(versionedChecks,
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "publish_dynamic_key_x5cs", "false"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information.city"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information.country"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information.organization"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information.organization_unit"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information.state"),
		)
	} else {
		versionedChecks = append(versionedChecks,
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "publish_dynamic_key_x5cs"),
			resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "dynamic_key_certificate_information"),
		)
	}
	return resource.ComposeTestCheckFunc(versionedChecks...)
}

// Validate any computed values when applying complete HCL
func keypairsOauthOpenidConnect_CheckComputedValuesComplete() resource.TestCheckFunc {
	if acctest.VersionAtLeast(version.PingFederate1201) {
		return resource.ComposeTestCheckFunc(
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p256_publish_x5c_parameter", "false"),
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p384_publish_x5c_parameter", "false"),
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p521_decryption_publish_x5c_parameter", "false"),
			resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_decryption_publish_x5c_parameter", "false"),
		)
	}
	return resource.ComposeTestCheckFunc(
		resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p256_publish_x5c_parameter", "false"),
		resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p384_publish_x5c_parameter", "false"),
		resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "p521_decryption_publish_x5c_parameter", "false"),
		resource.TestCheckResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_decryption_publish_x5c_parameter", "false"),
		resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_active_key_ids"),
		resource.TestCheckNoResourceAttr("pingfederate_keypairs_oauth_openid_connect.example", "rsa_algorithm_previous_key_ids"),
	)
}
