// Code generated by ping-terraform-plugin-framework-generator

package serversettingswstruststssettings

import (
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	emptyStringListDefault, _  = types.ListValue(types.StringType, nil)
	resourceLinkListDefault, _ = types.ListValue(types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"id": types.StringType,
		},
	}, nil)
	usersListDefault, _ = types.ListValue(types.ObjectType{
		AttrTypes: map[string]attr.Type{
			"username": types.StringType,
			"password": types.StringType,
		},
	}, nil)
)
